### ISSUE TITLE
New template for batch execution

### ISSUE THREAD

**Issue by TaoSunVoyage** [SwissDataScienceCenter/renku-project-template#118]
For batch execution described in SwissDataScienceCenter/renku/issues/1929, we suggest to create a new template. 

Compare to the original template, this one:
- w/   `Dockerfile.batch` - based on a batch version image SwissDataScienceCenter/renkulab-docker/issues/172
- w/o `environment.yml` - not to use conda for dependencies
- extra job in `.gitlab-ci.yml` to build and push the batch image automatically

Such template can be useful for batch execution with commands proposed in SwissDataScienceCenter/renku-python/issues/2213

`Dockerfile.batch`, for example:

```Dockerfile
ARG RENKU_BASE_IMAGE=renku/renkulab-batch
FROM ${RENKU_BASE_IMAGE}

# Uncomment and adapt if code is to be included in the image
# COPY src /code/src

# Uncomment and adapt if your R or python packages require extra linux (ubuntu) software
# e.g. the following installs apt-utils and vim; each pkg on its own line, all lines
# except for the last end with backslash '\' to continue the RUN line
#
# USER root
# RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    apt-utils \
#    vim
# USER ${NB_USER}

# install the python dependencies
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

# RENKU_VERSION determines the version of the renku CLI
# that will be used in this image. To find the latest version,
# visit https://pypi.org/project/renku/#history.
ARG RENKU_VERSION=0.15.1

########################################################
# Do not edit this section and do not add anything below

RUN if [ -n "$RENKU_VERSION" ] ; then \
    pipx uninstall renku && \
    pipx install --force renku==${RENKU_VERSION} \
    ; fi

########################################################
```

Extra job in `.gitlab-ci.yml`, for example:
```yaml
batch_image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7-batch -f Dockerfile.batch .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7-batch
```
