### ISSUE TITLE
Include variables in manifest

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-project-template#67]
Include template's available variables in the `manifest.yaml` with a short description.

E.G.
  ```
- folder: python-cuda
  variables:
    - description: a short description going in the Readme file
    - cuda-version: specify cuda version (only 9.x or 10.x)
 ```
